### ISSUE TITLE
Build error on arm. When Zenbot compiles fine.

### ISSUE THREAD

**Issue by tsrnc2** [carlos8f/bot18#2]
/root/.npm/_npx/15936/lib/node_modules/bot18/node_modules/js-scrypt/lib/scrypt-async.js:4
var cpu_count = require('os').cpus().length;
                                    ^

TypeError: Cannot read property 'length' of undefined
    at Object.<anonymous> (/root/.npm/_npx/15936/lib/node_modules/bot18/node_modules/js-scrypt/lib/scrypt-async.js:4:37)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/.npm/_npx/15936/lib/node_modules/bot18/node_modules/js-scrypt/index.js:2:8)
    at Module._compile (module.js:652:30)

**Comment by tsrnc2** [comment]
npm install 
fixed the issue for me

**Comment by tsrnc2** [comment]
Seems this is a known node error with arm64 and require('os').cpus().length
Perhaps you could add a line to the config file so the number of cores can be set manually.

**Comment by GarethWright** [comment]
require('os').cpus().length; looks for logical cores rather than physical ones.
That can actually cause a higher latency on multi-threaded apps as two processes share the same physical core.

**Comment by fabiosantoscode** [comment]
https://www.npmjs.com/package/physical-cpu-count
